ci:
  autoupdate_schedule: monthly
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.15.9'
  hooks:
    # Run the formatter.
    - id: ruff-format
    # Run the linter.
    - id: ruff-check
      args: [--fix]
- repo: https://github.com/codespell-project/codespell
  rev: 'v2.4.2'
  hooks:
    - id: codespell
      files: \.(py|rst|md)$
      args: [--ignore-words-list=set]
- repo: https://github.com/adhtruong/mirrors-typos
  # Use mirror to avoid autoupdate issue: https://github.com/crate-ci/typos/issues/390
  rev: 'v1.46.0'
  hooks:
    - id: typos
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: name-tests-test
  -   id: no-commit-to-branch
  -   id: end-of-file-fixer
      exclude: .svg$
